// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>
#include <vector>

using namespace std;
using namespace Rcpp;

// HC_fused_cpp_opt6
vector<vector<int>> HC_fused_cpp_opt6(vector<vector<int>> MAT, int n_iter);
RcppExport SEXP _HCfused_HC_fused_cpp_opt6(SEXP MATSEXP, SEXP n_iterSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< vector<vector<int>> >::type MAT(MATSEXP);
    Rcpp::traits::input_parameter< int >::type n_iter(n_iterSEXP);
    rcpp_result_gen = Rcpp::wrap(HC_fused_cpp_opt6(MAT, n_iter));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_HCfused_HC_fused_cpp_opt6", (DL_FUNC) &_HCfused_HC_fused_cpp_opt6, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_HCfused(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
