# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

HC_fused_cpp_opt6 <- function(MAT, n_iter) {
    .Call(`_HCfused_HC_fused_cpp_opt6`, MAT, n_iter)
}

